# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameradetails',
            fields=[
                ('cam_location', models.CharField(max_length=255)),
                ('cam_event_id', models.IntegerField()),
                ('cam_pid', models.IntegerField(primary_key=True, serialize=False)),
                ('camera_typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eventdetails',
            fields=[
                ('event_type', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('cameras_num', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
